name: GetNBT
main: xyz.tangledwires.GetNBT.GetNBT
version: 1.0.0
author: xWires
commands:
   getnbt:
      description: Get the metadata of the item you are holding
      usage: /getnbt
      permission: GetNBT.getnbt
      permission-message: You don't have permission to use this command.